<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <joint name="lidar_joint" type="fixed">
        <parent link="chassis"/>
        <child link="lidar_frame"/>
        <origin xyz="${chassis_length/2} 0 ${chassis_height+.03}" rpy="0 0.087266 0"/>
    </joint>

    <link name="lidar_frame">
        <visual>
            <geometry> 
                <cylinder radius="0.0508" length="0.0508"/> <!-- Convert inches to meters -->
            </geometry>
            <material name="purple"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.0508" length="0.0508"/> <!-- Convert inches to meters -->
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" length="0.05" radius="0.0254"> <!-- Convert inches to meters -->
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>



    <gazebo reference="lidar_frame">
        <material>Gazebo/Black</material>

        <sensor name="lidar" type="ray">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>true</visualize>
            <update_rate>10</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <min_angle>-3.14</min_angle>
                        <max_angle>3.14</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.3</min>
                    <max>12</max>
                </range>
            </ray>
            <plugin name="lidar_controller" filename="libgazebo_ros_ray_sensor.so">
                <ros>
                    <argument>~/out:=scan</argument>
                </ros>
                <output_type>sensor_msgs/LaserScan</output_type>
                <frame_name>lidar_frame</frame_name>
            </plugin>
        </sensor>
    </gazebo>


</robot>
